### ISSUE TITLE
Style CSS in Arabic Website

### ISSUE THREAD

**Issue by Kiwifu** [NicBeltramelli/genesis-advanced#1]
Hi dear,

Thank you for that great effort.

I test it your theme on My blog : [موقع كيوي](https://www.kiwifu.com), but i think there is an issue with Style.css, something is missing there.

Regards

Badr

**Comment by NicBeltramelli** [comment]
Hi Badr and thanks for testing my theme,
The style.css file is only used to contain the theme meta informations, all CSS files are in the assets folder and will be compiled to the dist folder by launching the 'yarn build' command (make sure you have all the dependencies installed). The dist folder is gitignored, as it contains compiled files.
